In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
import datetime
import scipy.stats as stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
import warnings

%matplotlib inline
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
sns.set(style="darkgrid")

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
os.chdir("/content/drive/My Drive")
!ls

'1 Survey Delivery Playbook - Proposal and Commissioning.pdf'
'2 Survey Delivery Playbook - Research and Implementation Design.pdf'
 311_clean_data.csv
'311_Service_Requests_from_2010_to_Present_2022 data.csv'
'3 Survey Delivery Playbook - Execution.pdf'
'4 Survey Delivery Playbook - Fieldwork Management.pdf'
'5 Survey Delivery Playbook - Deliverables.pdf'
'6 Survey Delivery Playbook - Wrap Up.pdf'
'Colab Notebooks'
'EB list Canada 2022_v1.0- final file.xlsx'
'EB list India 2022_v1.0 - Final.xlsx'
'EB list USA 2022_v1.0.xlsx'
'English Version Offerte USG People NPS in perspectief op merkniveau Final.nl.en.pdf'
'Final REBR Research Manual 2021 (1).pptx'
 IN_RandstadEmployerBrandingCalculation.xlsx
'Kantar Proposal - Body  Fit Pack_244409035 Redesign Test 12022021 (002).pptx'
'Kantar proposal for Philips - Xian Validation study.pdf'
'KNL - CX - TRIM + NPS USG_FINAL INTERNAL VERSION_210419.docx'
'KNL - CX - TRIM + NPS USG_FINAL.nl.en.docx'
'Master Questionnaire Randstad Employer Brand Research 2022_v6_CAWI (1).docx'
'Master Questionnaire REBR 2022_script checks.docx'
 MX_RandstadEmployerBrandingCalculation.xlsx
 NO_RandstadEmployerBrandingCalculation.xlsx
'REBR Playbook_v3.pptx'
 ScriptGenie_O.xlsm
'Survey Delivery Snake Flow Chart 2012-07D - PM Offshore.pdf'
 Unzipped
'Unzipped (1)'
 Unzipped-Subjects

In [4]:
link = "https://drive.google.com/file/d/1sFO9OSvGD8OGU9aofSSkVd8iX_kDSOj9/view?usp=share_link"

In [6]:
df = pd.read_csv("311_Service_Requests_from_2010_to_Present_2022 data.csv")

In [7]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,BBL,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Open Data Channel Type,Park Facility Name,Park Borough,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,52940375,01/01/2022 12:00:00 AM,01/03/2022 08:39:00 AM,DEP,Department of Environmental Protection,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",NaN,10036.0,640 8 AVENUE,8 AVENUE,W 41 ST,W 42 ST,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,NaN,The Department of Environmental Protection det...,01/03/2022 08:39:00 AM,05 MANHATTAN,1.010138e+09,MANHATTAN,986967.0,214950.0,ONLINE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.756664,-73.990193,"(40.75666417742652, -73.99019293432467)"
1,52934953,01/01/2022 12:00:10 AM,01/01/2022 01:00:11 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11222.0,126 DRIGGS AVENUE,DRIGGS AVENUE,NORTH HENRY STREET,RUSSELL STREET,NORTH HENRY STREET,RUSSELL STREET,ADDRESS,BROOKLYN,DRIGGS AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 01:00:15 AM,01 BROOKLYN,NaN,BROOKLYN,999866.0,202742.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.723143,-73.943662,"(40.72314288436064, -73.94366208445774)"
2,52933158,01/01/2022 12:00:57 AM,01/01/2022 12:58:22 AM,NYPD,New York City Police Department,Noise - Residential,Loud Talking,Residential Building/House,11214.0,45 BAY 38 STREET,BAY 38 STREET,86 STREET,BENSON AVENUE,86 STREET,BENSON AVENUE,ADDRESS,BROOKLYN,BAY 38 STREET,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:58:29 AM,11 BROOKLYN,3.068668e+09,BROOKLYN,987344.0,156952.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.597473,-73.988859,"(40.59747269272421, -73.98885877127528)"
3,52938624,01/01/2022 12:01:04 AM,01/01/2022 12:18:49 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10025.0,998 AMSTERDAM AVENUE,AMSTERDAM AVENUE,WEST 109 STREET,CATHEDRAL PARKWAY,WEST 109 STREET,CATHEDRAL PARKWAY,ADDRESS,NEW YORK,AMSTERDAM AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:18:55 AM,07 MANHATTAN,1.018810e+09,MANHATTAN,994168.0,231674.0,MOBILE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.802562,-73.964176,"(40.80256198626038, -73.96417609586966)"
4,52931678,01/01/2022 12:01:17 AM,01/01/2022 02:55:16 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10456.0,974 SHERIDAN AVENUE,SHERIDAN AVENUE,EAST 163 STREET,EAST 164 STREET,EAST 163 STREET,EAST 164 STREET,ADDRESS,BRONX,SHERIDAN AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 02:55:25 AM,04 BRONX,2.024550e+09,BRONX,1006601.0,241609.0,ONLINE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.829808,-73.919235,"(40.82980806226658, -73.91923492133385)"

In [9]:
df.shape

(2653377, 41)

In [10]:
display(df.head())
df.shape

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,BBL,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Open Data Channel Type,Park Facility Name,Park Borough,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,52940375,01/01/2022 12:00:00 AM,01/03/2022 08:39:00 AM,DEP,Department of Environmental Protection,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",NaN,10036.0,640 8 AVENUE,8 AVENUE,W 41 ST,W 42 ST,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,NaN,The Department of Environmental Protection det...,01/03/2022 08:39:00 AM,05 MANHATTAN,1.010138e+09,MANHATTAN,986967.0,214950.0,ONLINE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.756664,-73.990193,"(40.75666417742652, -73.99019293432467)"
1,52934953,01/01/2022 12:00:10 AM,01/01/2022 01:00:11 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11222.0,126 DRIGGS AVENUE,DRIGGS AVENUE,NORTH HENRY STREET,RUSSELL STREET,NORTH HENRY STREET,RUSSELL STREET,ADDRESS,BROOKLYN,DRIGGS AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 01:00:15 AM,01 BROOKLYN,NaN,BROOKLYN,999866.0,202742.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.723143,-73.943662,"(40.72314288436064, -73.94366208445774)"
2,52933158,01/01/2022 12:00:57 AM,01/01/2022 12:58:22 AM,NYPD,New York City Police Department,Noise - Residential,Loud Talking,Residential Building/House,11214.0,45 BAY 38 STREET,BAY 38 STREET,86 STREET,BENSON AVENUE,86 STREET,BENSON AVENUE,ADDRESS,BROOKLYN,BAY 38 STREET,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:58:29 AM,11 BROOKLYN,3.068668e+09,BROOKLYN,987344.0,156952.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.597473,-73.988859,"(40.59747269272421, -73.98885877127528)"
3,52938624,01/01/2022 12:01:04 AM,01/01/2022 12:18:49 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10025.0,998 AMSTERDAM AVENUE,AMSTERDAM AVENUE,WEST 109 STREET,CATHEDRAL PARKWAY,WEST 109 STREET,CATHEDRAL PARKWAY,ADDRESS,NEW YORK,AMSTERDAM AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:18:55 AM,07 MANHATTAN,1.018810e+09,MANHATTAN,994168.0,231674.0,MOBILE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.802562,-73.964176,"(40.80256198626038, -73.96417609586966)"
4,52931678,01/01/2022 12:01:17 AM,01/01/2022 02:55:16 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10456.0,974 SHERIDAN AVENUE,SHERIDAN AVENUE,EAST 163 STREET,EAST 164 STREET,EAST 163 STREET,EAST 164 STREET,ADDRESS,BRONX,SHERIDAN AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 02:55:25 AM,04 BRONX,2.024550e+09,BRONX,1006601.0,241609.0,ONLINE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.829808,-73.919235,"(40.82980806226658, -73.91923492133385)"

(2653377, 41)

Dealing with Missing and Superfluous Data
Let's check the column data types and identify columns with missing values.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2653377 entries, 0 to 2653376
Data columns (total 41 columns):
 #   Column                          Dtype
---  ------                          -----
 0   Unique Key                      int64
 1   Created Date                    object
 2   Closed Date                     object
 3   Agency                          object
 4   Agency Name                     object
 5   Complaint Type                  object
 6   Descriptor                      object
 7   Location Type                   object
 8   Incident Zip                    float64
 9   Incident Address                object
 10  Street Name                     object
 11  Cross Street 1                  object
 12  Cross Street 2                  object
 13  Intersection Street 1           object
 14  Intersection Street 2           object
 15  Address Type                    object
 16  City                            object
 17  Landmark                        object
 18  Facility Type                   object
 19  Status                          object
 20  Due Date                        object
 21  Resolution Description          object
 22  Resolution Action Updated Date  object
 23  Community Board                 object
 24  BBL                             float64
 25  Borough                         object
 26  X Coordinate (State Plane)      float64
 27  Y Coordinate (State Plane)      float64
 28  Open Data Channel Type          object
 29  Park Facility Name              object
 30  Park Borough                    object
 31  Vehicle Type                    object
 32  Taxi Company Borough            object
 33  Taxi Pick Up Location           object
 34  Bridge Highway Name             object
 35  Bridge Highway Direction        object
 36  Road Ramp                       object
 37  Bridge Highway Segment          object
 38  Latitude                        float64
 39  Longitude                       float64
 40  Location                        object
dtypes: float64(6), int64(1), object(34)
memory usage: 830.0+ MB

Renaming the columns and removing space in the column names

In [19]:
for col in df.columns:
    df.rename(columns={col:col.lower().replace(" ","_")},inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2525144 entries, 0 to 2653376
Data columns (total 41 columns):
 #   Column                          Dtype
---  ------                          -----
 0   unique_key                      int64
 1   created_date                    object
 2   closed_date                     object
 3   agency                          object
 4   agency_name                     object
 5   complaint_type                  object
 6   descriptor                      object
 7   location_type                   object
 8   incident_zip                    float64
 9   incident_address                object
 10  street_name                     object
 11  cross_street_1                  object
 12  cross_street_2                  object
 13  intersection_street_1           object
 14  intersection_street_2           object
 15  address_type                    object
 16  city                            object
 17  landmark                        object
 18  facility_type                   object
 19  status                          object
 20  due_date                        object
 21  resolution_description          object
 22  resolution_action_updated_date  object
 23  community_board                 object
 24  bbl                             float64
 25  borough                         object
 26  x_coordinate_(state_plane)      float64
 27  y_coordinate_(state_plane)      float64
 28  open_data_channel_type          object
 29  park_facility_name              object
 30  park_borough                    object
 31  vehicle_type                    object
 32  taxi_company_borough            object
 33  taxi_pick_up_location           object
 34  bridge_highway_name             object
 35  bridge_highway_direction        object
 36  road_ramp                       object
 37  bridge_highway_segment          object
 38  latitude                        float64
 39  longitude                       float64
 40  location                        object
dtypes: float64(6), int64(1), object(34)
memory usage: 809.1+ MB

In [21]:
#eliminate rows without lat/long and location type data
df = df[df.latitude.notnull()]
df = df[df.longitude.notnull()]
df = df[df.descriptor.notnull()]

Reformatting Values for Consistency

In [22]:
df.complaint_type.unique()

array(['Air Quality', 'Noise - Street/Sidewalk', 'Noise - Residential',
       'Noise - Vehicle', 'Rodent', 'Homeless Person Assistance',
       'Illegal Parking', 'Request Large Bulky Item Collection',
       'Noise - Commercial', 'Blocked Driveway', 'New Tree Request',
       'Street Condition', 'HEAT/HOT WATER', 'GENERAL', 'WATER LEAK',
       'PLUMBING', 'UNSANITARY CONDITION', 'Noise - Park',
       'Unsanitary Animal Pvt Property', 'Sidewalk Condition',
       'Dirty Condition', 'PAINT/PLASTER', 'ELECTRIC',
       'Electronics Waste Appointment', 'Noise', 'Graffiti',
       'Building/Use', 'Non-Emergency Police Matter', 'Lead',
       'Non-Residential Heat', 'Face Covering Violation', 'Lost Property',
       'Illegal Tree Damage', 'Root/Sewer/Sidewalk Condition',
       'Street Light Condition', 'Drinking', 'Taxi Complaint', 'Traffic',
       'Smoking', 'Indoor Air Quality', 'Drug Activity', 'DOOR/WINDOW',
       'FLOORING/STAIRS', 'Sewer', 'Abandoned Vehicle',
       'Consumer Complaint', 'Food Establishment',
       'For Hire Vehicle Complaint', 'Illegal Dumping',
       'Traffic Signal Condition', 'Water System', 'Missed Collection',
       'General Construction/Plumbing', 'Litter Basket Request',
       'Unleashed Dog', 'Mobile Food Vendor', 'Street Sign - Damaged',
       'Obstruction', 'Litter Basket Complaint', 'Food Poisoning',
       'Special Projects Inspection Team (SPIT)', 'Dead Animal',
       'Maintenance or Facility', 'Vaccine Mandate Non-Compliance',
       'APPLIANCE', 'Residential Disposal Complaint', 'Animal in a Park',
       'Street Sign - Dangling', 'Elevator', 'Water Conservation',
       'Bus Stop Shelter Complaint', 'Animal-Abuse', 'Damaged Tree',
       'ELEVATOR', 'For Hire Vehicle Report', 'Street Sign - Missing',
       'Violation of Park Rules', 'Derelict Vehicles',
       'Broken Parking Meter', 'Real Time Enforcement', 'Boilers',
       'Noise - House of Worship', 'OUTSIDE BUILDING', 'Industrial Waste',
       'Curb Condition', 'Dead/Dying Tree', 'Mold', 'Dumpster Complaint',
       'SAFETY', 'Emergency Response Team (ERT)',
       'Unsanitary Animal Facility', 'Abandoned Bike', 'Illegal Posting',
       'Electrical', 'Water Quality', 'Outdoor Dining',
       'Overgrown Tree/Branches', 'Bus Stop Shelter Placement',
       'Lot Condition', 'Street Sweeping Complaint',
       'Institution Disposal Complaint', 'Illegal Animal Kept as Pet',
       'Incorrect Data', 'Asbestos', 'Day Care', 'Posting Advertisement',
       'Noise - Helicopter', 'Disorderly Youth', 'Harboring Bees/Wasps',
       'Hazardous Materials', 'Taxi Report', 'Plumbing',
       'Construction Lead Dust', 'Snow or Ice', 'School Maintenance',
       'Sanitation Worker or Vehicle Complaint', 'BEST/Site Safety',
       'Uprooted Stump', 'Unsanitary Pigeon Condition', 'Drinking Water',
       'Indoor Sewage', 'Illegal Animal Sold',
       'Beach/Pool/Sauna Complaint', 'Wood Pile Remaining',
       'Private School Vaccine Mandate Non-Compliance',
       'Investigations and Discipline (IAD)', 'Adopt-A-Basket',
       'Commercial Disposal Complaint', 'E-Scooter',
       'Green Taxi Complaint', 'Taxi Compliment', 'AHV Inspection Unit',
       'Tattooing', 'Pet Shop', 'Bike Rack Condition', 'Scaffold Safety',
       'Window Guard', 'Recycling Basket Complaint', 'Bottled Water',
       'Borough Office', 'LinkNYC', 'Plant', 'Found Property',
       'Cranes and Derricks', 'Cooling Tower', 'X-Ray Machine/Equipment',
       'Oil or Gas Spill', 'Retailer Complaint', 'FHV Licensee Complaint',
       'Special Natural Area District (SNAD)', 'Seasonal Collection',
       'Facade Insp Safety Pgm', 'Building Marshals office',
       'Dept of Investigations', 'DEP Street Condition',
       'Public Payphone Complaint', 'Building Condition',
       'Dispatched Taxi Compliment', 'Radioactive Material',
       'Public Toilet', 'Mass Gathering Complaint', 'Tanning',
       'Dispatched Taxi Complaint', 'COVID-19 Non-essential Construction',
       'Mosquitoes', 'Highway Condition', 'Facades', 'Standing Water',
       'Calorie Labeling', 'DEP Highway Condition',
       'Transfer Station Complaint', 'Taxi Licensee Complaint',
       'Municipal Parking Facility', 'Lifeguard',
       'Building Drinking Water Tank', 'Green Taxi Report',
       'Internal Code', 'Special Operations', 'DEP Sidewalk Condition',
       'ZTESTINT', 'DSNY Internal'], dtype=object)

In [23]:
df.complaint_type = df.complaint_type.str.title()

In [25]:
df.agency.unique()

array(['DEP', 'NYPD', 'DOHMH', 'DHS', 'DSNY', 'DPR', 'DOT', 'HPD', 'DOB',
       'TLC', 'DCA', 'EDC', 'DOE', 'OTI'], dtype=object)

Among noise-related complaints, only one does not specify the noise source:

In [26]:
noise_columns = []

for i in df.complaint_type:
   if i.startswith('Noise') and i not in noise_columns:
     noise_columns.append(i)
noise_columns

['Noise - Street/Sidewalk',
 'Noise - Residential',
 'Noise - Vehicle',
 'Noise - Commercial',
 'Noise - Park',
 'Noise',
 'Noise - House Of Worship',
 'Noise - Helicopter']

We'll convert the generic 'Noise' value to 'Noise - Unspecified' so that its formatting matches that of similar complaint types.

In [27]:
#Label unspecified noise complaints as 'Noise - Unspecified'

def update_noise(complaint):

  """Takes in an complaint name and updates it, if it is
     an unspecified noise complaint."""

  if complaint == 'Noise':
    
    return "Noise - Unspecified"

  else:

    return complaint
    
df.complaint_type = df.complaint_type.map(
    lambda complaint: update_noise(complaint))

The 'created_date' column currently contains string values:

In [29]:
type(df.created_date[1])

str

In [32]:
import datetime

In [35]:
# convert dates to datetime and zip codes into strings
df.created_date = pd.to_datetime(df.created_date)
df.closed_date = pd.to_datetime(df.closed_date)

In [36]:
#check new data type for created_date column
type(df['created_date'][1])

pandas._libs.tslibs.timestamps.Timestamp

In [37]:
df['day'] = [str(i.date()) for i in df.created_date]
df['month'] = [int(i.month) for i in df.created_date]
df['day_of_week'] = [int(i.weekday()) for i in df.created_date]
df['hour'] = [int(i.hour) for i in df.created_date]

In [41]:
#reorder df from least-most recent calls
df = df.reindex(index=df.index[::-1])

In [42]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,day,month,day_of_week,hour
0,52940375,2022-01-01 00:00:00,2022-01-03 08:39:00,DEP,Department of Environmental Protection,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",NaN,10036.0,640 8 AVENUE,8 AVENUE,W 41 ST,W 42 ST,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,NaN,The Department of Environmental Protection det...,01/03/2022 08:39:00 AM,05 MANHATTAN,1.010138e+09,MANHATTAN,986967.0,214950.0,ONLINE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.756664,-73.990193,"(40.75666417742652, -73.99019293432467)",2022-01-01,1,5,0
1,52934953,2022-01-01 00:00:10,2022-01-01 01:00:11,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11222.0,126 DRIGGS AVENUE,DRIGGS AVENUE,NORTH HENRY STREET,RUSSELL STREET,NORTH HENRY STREET,RUSSELL STREET,ADDRESS,BROOKLYN,DRIGGS AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 01:00:15 AM,01 BROOKLYN,NaN,BROOKLYN,999866.0,202742.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.723143,-73.943662,"(40.72314288436064, -73.94366208445774)",2022-01-01,1,5,0
2,52933158,2022-01-01 00:00:57,2022-01-01 00:58:22,NYPD,New York City Police Department,Noise - Residential,Loud Talking,Residential Building/House,11214.0,45 BAY 38 STREET,BAY 38 STREET,86 STREET,BENSON AVENUE,86 STREET,BENSON AVENUE,ADDRESS,BROOKLYN,BAY 38 STREET,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:58:29 AM,11 BROOKLYN,3.068668e+09,BROOKLYN,987344.0,156952.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.597473,-73.988859,"(40.59747269272421, -73.98885877127528)",2022-01-01,1,5,0
3,52938624,2022-01-01 00:01:04,2022-01-01 00:18:49,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10025.0,998 AMSTERDAM AVENUE,AMSTERDAM AVENUE,WEST 109 STREET,CATHEDRAL PARKWAY,WEST 109 STREET,CATHEDRAL PARKWAY,ADDRESS,NEW YORK,AMSTERDAM AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:18:55 AM,07 MANHATTAN,1.018810e+09,MANHATTAN,994168.0,231674.0,MOBILE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.802562,-73.964176,"(40.80256198626038, -73.96417609586966)",2022-01-01,1,5,0
4,52931678,2022-01-01 00:01:17,2022-01-01 02:55:16,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10456.0,974 SHERIDAN AVENUE,SHERIDAN AVENUE,EAST 163 STREET,EAST 164 STREET,EAST 163 STREET,EAST 164 STREET,ADDRESS,BRONX,SHERIDAN AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 02:55:25 AM,04 BRONX,2.024550e+09,BRONX,1006601.0,241609.0,ONLINE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.829808,-73.919235,"(40.82980806226658, -73.91923492133385)",2022-01-01,1,5,0

In [45]:
# calculate the response time in days
df['response_time'] = df.closed_date - df.created_date
df['response_time'] = df['response_time'] / np.timedelta64(1,'D')

# remove the records with invalid response times (less that zero)
df = df[df['response_time'] > 0]

df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,street_name,cross_street_1,cross_street_2,intersection_street_1,intersection_street_2,address_type,city,landmark,facility_type,status,due_date,resolution_description,resolution_action_updated_date,community_board,bbl,borough,x_coordinate_(state_plane),y_coordinate_(state_plane),open_data_channel_type,park_facility_name,park_borough,vehicle_type,taxi_company_borough,taxi_pick_up_location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,latitude,longitude,location,day,month,day_of_week,hour,closed_day,response_time
0,52940375,2022-01-01 00:00:00,2022-01-03 08:39:00,DEP,Department of Environmental Protection,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",NaN,10036.0,640 8 AVENUE,8 AVENUE,W 41 ST,W 42 ST,NaN,NaN,ADDRESS,NEW YORK,NaN,NaN,Closed,NaN,The Department of Environmental Protection det...,01/03/2022 08:39:00 AM,05 MANHATTAN,1.010138e+09,MANHATTAN,986967.0,214950.0,ONLINE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.756664,-73.990193,"(40.75666417742652, -73.99019293432467)",2022-01-01,1,5,0,2022-01-03,2.360417
1,52934953,2022-01-01 00:00:10,2022-01-01 01:00:11,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11222.0,126 DRIGGS AVENUE,DRIGGS AVENUE,NORTH HENRY STREET,RUSSELL STREET,NORTH HENRY STREET,RUSSELL STREET,ADDRESS,BROOKLYN,DRIGGS AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 01:00:15 AM,01 BROOKLYN,NaN,BROOKLYN,999866.0,202742.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.723143,-73.943662,"(40.72314288436064, -73.94366208445774)",2022-01-01,1,5,0,2022-01-01,0.041678
2,52933158,2022-01-01 00:00:57,2022-01-01 00:58:22,NYPD,New York City Police Department,Noise - Residential,Loud Talking,Residential Building/House,11214.0,45 BAY 38 STREET,BAY 38 STREET,86 STREET,BENSON AVENUE,86 STREET,BENSON AVENUE,ADDRESS,BROOKLYN,BAY 38 STREET,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:58:29 AM,11 BROOKLYN,3.068668e+09,BROOKLYN,987344.0,156952.0,MOBILE,Unspecified,BROOKLYN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.597473,-73.988859,"(40.59747269272421, -73.98885877127528)",2022-01-01,1,5,0,2022-01-01,0.039873
3,52938624,2022-01-01 00:01:04,2022-01-01 00:18:49,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10025.0,998 AMSTERDAM AVENUE,AMSTERDAM AVENUE,WEST 109 STREET,CATHEDRAL PARKWAY,WEST 109 STREET,CATHEDRAL PARKWAY,ADDRESS,NEW YORK,AMSTERDAM AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 12:18:55 AM,07 MANHATTAN,1.018810e+09,MANHATTAN,994168.0,231674.0,MOBILE,Unspecified,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.802562,-73.964176,"(40.80256198626038, -73.96417609586966)",2022-01-01,1,5,0,2022-01-01,0.012326
4,52931678,2022-01-01 00:01:17,2022-01-01 02:55:16,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10456.0,974 SHERIDAN AVENUE,SHERIDAN AVENUE,EAST 163 STREET,EAST 164 STREET,EAST 163 STREET,EAST 164 STREET,ADDRESS,BRONX,SHERIDAN AVENUE,NaN,Closed,NaN,The Police Department responded to the complai...,01/01/2022 02:55:25 AM,04 BRONX,2.024550e+09,BRONX,1006601.0,241609.0,ONLINE,Unspecified,BRONX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.829808,-73.919235,"(40.82980806226658, -73.91923492133385)",2022-01-01,1,5,0,2022-01-01,0.120822

In [46]:
# Count of non-null values for every column 
df_columns = list(df.columns)
df[df_columns].count()

unique_key                        2291243
created_date                      2291243
closed_date                       2291243
agency                            2291243
agency_name                       2291243
complaint_type                    2291243
descriptor                        2291243
location_type                     2032512
incident_zip                      2290851
incident_address                  2230908
street_name                       2230851
cross_street_1                    1673683
cross_street_2                    1674277
intersection_street_1             1525254
intersection_street_2             1526159
address_type                      2290925
city                              2204828
landmark                          1373983
facility_type                        8933
status                            2291243
due_date                             2907
resolution_description            2287039
resolution_action_updated_date    2290863
community_board                   2291243
bbl                               2079088
borough                           2291243
x_coordinate_(state_plane)        2291243
y_coordinate_(state_plane)        2291243
open_data_channel_type            2291243
park_facility_name                2291234
park_borough                      2291243
vehicle_type                          310
taxi_company_borough                  868
taxi_pick_up_location               17518
bridge_highway_name                   332
bridge_highway_direction              249
road_ramp                             203
bridge_highway_segment                328
latitude                          2291243
longitude                         2291243
location                          2291243
day                               2291243
month                             2291243
day_of_week                       2291243
hour                              2291243
closed_day                        2291243
response_time                     2291243
dtype: int64

In [47]:
# A list of columns to remove from the dataframe
df_cols_rmv = ['Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
               'Intersection Street 1', 'Intersection Street 2', 'Landmark', 'Facility Type',
               'Due Date', 'Resolution Description','Community Board', 'X Coordinate (State Plane)',
               'Y Coordinate (State Plane)', 'Park Facility Name', 'Park Borough', 'School Name',
               'School Number', 'School Region', 'School Code', 'School Phone Number', 'School Address',
               'School City', 'School State', 'School Zip', 'School Not Found', 'School or Citywide Complaint',
               'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name',
               'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment', 'Garage Lot Name',
               'Ferry Direction', 'Ferry Terminal Name', 'Address Type',
               'Resolution Action Updated Date']

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2291243 entries, 0 to 2653376
Data columns (total 47 columns):
 #   Column                          Dtype
---  ------                          -----
 0   unique_key                      int64
 1   created_date                    datetime64[ns]
 2   closed_date                     datetime64[ns]
 3   agency                          object
 4   agency_name                     object
 5   complaint_type                  object
 6   descriptor                      object
 7   location_type                   object
 8   incident_zip                    float64
 9   incident_address                object
 10  street_name                     object
 11  cross_street_1                  object
 12  cross_street_2                  object
 13  intersection_street_1           object
 14  intersection_street_2           object
 15  address_type                    object
 16  city                            object
 17  landmark                        object
 18  facility_type                   object
 19  status                          object
 20  due_date                        object
 21  resolution_description          object
 22  resolution_action_updated_date  object
 23  community_board                 object
 24  bbl                             float64
 25  borough                         object
 26  x_coordinate_(state_plane)      float64
 27  y_coordinate_(state_plane)      float64
 28  open_data_channel_type          object
 29  park_facility_name              object
 30  park_borough                    object
 31  vehicle_type                    object
 32  taxi_company_borough            object
 33  taxi_pick_up_location           object
 34  bridge_highway_name             object
 35  bridge_highway_direction        object
 36  road_ramp                       object
 37  bridge_highway_segment          object
 38  latitude                        float64
 39  longitude                       float64
 40  location                        object
 41  day                             object
 42  month                           int64
 43  day_of_week                     int64
 44  hour                            int64
 45  closed_day                      object
 46  response_time                   float64
dtypes: datetime64[ns](2), float64(7), int64(4), object(34)
memory usage: 839.1+ MB

In [53]:
# Remove the columns added to the df_cols_rmv list from df dataframe
df.drop(['incident_address', 'street_name', 'cross_street_1', 'cross_street_2',
               'intersection_street_1', 'intersection_street_2', 'landmark', 'facility_type',
               'due_date', 'resolution_description','community_board', 'x_coordinate_(state_plane)',
               'y_coordinate_(state_plane)', 'park_facility_name', 'park_borough',
               'vehicle_type', 'taxi_company_borough', 'taxi_pick_up_location', 'bridge_highway_name',
               'bridge_highway_direction', 'road_ramp', 'bridge_highway_segment',
               'address_type','resolution_action_updated_date'], inplace=True, axis=1)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2291243 entries, 0 to 2653376
Data columns (total 23 columns):
 #   Column                  Dtype
---  ------                  -----
 0   unique_key              int64
 1   created_date            datetime64[ns]
 2   closed_date             datetime64[ns]
 3   agency                  object
 4   agency_name             object
 5   complaint_type          object
 6   descriptor              object
 7   location_type           object
 8   incident_zip            float64
 9   city                    object
 10  status                  object
 11  bbl                     float64
 12  borough                 object
 13  open_data_channel_type  object
 14  latitude                float64
 15  longitude               float64
 16  location                object
 17  day                     object
 18  month                   int64
 19  day_of_week             int64
 20  hour                    int64
 21  closed_day              object
 22  response_time           float64
dtypes: datetime64[ns](2), float64(5), int64(4), object(12)
memory usage: 419.5+ MB

In [55]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,city,status,bbl,borough,open_data_channel_type,latitude,longitude,location,day,month,day_of_week,hour,closed_day,response_time
0,52940375,2022-01-01 00:00:00,2022-01-03 08:39:00,DEP,Department of Environmental Protection,Air Quality,"Air: Odor/Fumes, Vehicle Idling (AD3)",NaN,10036.0,NEW YORK,Closed,1.010138e+09,MANHATTAN,ONLINE,40.756664,-73.990193,"(40.75666417742652, -73.99019293432467)",2022-01-01,1,5,0,2022-01-03,2.360417
1,52934953,2022-01-01 00:00:10,2022-01-01 01:00:11,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11222.0,BROOKLYN,Closed,NaN,BROOKLYN,MOBILE,40.723143,-73.943662,"(40.72314288436064, -73.94366208445774)",2022-01-01,1,5,0,2022-01-01,0.041678
2,52933158,2022-01-01 00:00:57,2022-01-01 00:58:22,NYPD,New York City Police Department,Noise - Residential,Loud Talking,Residential Building/House,11214.0,BROOKLYN,Closed,3.068668e+09,BROOKLYN,MOBILE,40.597473,-73.988859,"(40.59747269272421, -73.98885877127528)",2022-01-01,1,5,0,2022-01-01,0.039873
3,52938624,2022-01-01 00:01:04,2022-01-01 00:18:49,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10025.0,NEW YORK,Closed,1.018810e+09,MANHATTAN,MOBILE,40.802562,-73.964176,"(40.80256198626038, -73.96417609586966)",2022-01-01,1,5,0,2022-01-01,0.012326
4,52931678,2022-01-01 00:01:17,2022-01-01 02:55:16,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10456.0,BRONX,Closed,2.024550e+09,BRONX,ONLINE,40.829808,-73.919235,"(40.82980806226658, -73.91923492133385)",2022-01-01,1,5,0,2022-01-01,0.120822

In [57]:
#Explore Incident Zip
df['incident_zip'].unique()

array([10036., 11222., 11214., 10025., 10456., 10026., 11236., 11694.,
       11234., 11207., 11230., 11228., 11377., 11362., 11229., 10027.,
       11225., 11106., 10030., 11361., 10462., 10312., 11232., 10472.,
       11423., 11432., 10461., 11356., 11221., 11215., 10040., 11372.,
       10033., 11239., 11216., 11206., 11208., 10473., 10452., 10302.,
       10451., 11366., 10460., 10002., 10305., 10031., 10016., 11379.,
       11354., 11373., 10453., 11368., 11358., 11204., 11212., 10466.,
       11693., 10021., 10457., 10463., 11209., 10468., 10001., 11237.,
       10011., 10028., 11103., 10014., 11205., 10314., 11365., 11692.,
       11201., 10034., 11226., 11203., 11213., 11369., 10029., 11357.,
       11219., 11417., 11217., 10044., 11420., 10455., 10471., 11355.,
       10306., 11102., 10023., 11429., 11223., 11374., 11375., 10469.,
       10459., 10458., 11235., 10467., 11211., 10309., 10039., 11224.,
       11428., 10310., 11101., 11378., 11233., 11412., 10013., 11419.,
       11218., 11249., 11415., 11238., 11435., 10301., 10304., 11436.,
       11220., 11385., 11413., 11418., 10465., 11370., 10010., 11434.,
       10035., 10032., 10303., 11421., 11105., 10024., 10003., 11104.,
       11367., 11422., 11691., 10012., 11416., 10009., 10075., 10307.,
       11433., 11210., 10019., 10128., 10454., 10475., 10022., 10470.,
       10037., 11427., 10038., 11363., 10474., 11364., 11109., 10069.,
       11231., 10017., 11004., 10007., 10282., 11411., 10018., 11426.,
       10308., 11414., 11001., 10065., 10006., 11040., 11359., 10119.,
       11430., 11360., 10005., 10000., 10121., 10464., 10020., 10280.,
       11697., 10004., 10278., 10158., 12345., 10153., 11005., 10168.,
       10169., 10118., 10154., 10281., 10103., 10167., 10271., 10176.,
          nan, 10106., 10162., 10110., 10174., 10179., 10165., 10123.,
       10173., 11251., 10055., 10105., 11695., 10175., 11241., 10045.,
       10151., 10111., 11371., 10279., 10041., 10172., 10120., 11242.,
       10178., 10171., 10166., 10107., 10170.,    83., 10112., 10155.,
       10177., 10152., 10115., 10048., 10122.])

Its clear to see that Incident Zip has some issues other than the mixed data types, these issues are:
Mixed data types, sometimes floats, sometimes strings
Some on the zipcodes have 4 digits added to it after an hyphen
Some zipcodes are nan, others are ?, UNKNOWN, ANONYMOUS and so on

In [58]:
# Function that cleans the Incident Zip values and returns nan for data that cannot be cleaned
def correct_zip(zip_code):
    try:
        zip_code = int(float(zip_code))
    except:
        try:
            zip_code = int(float(zip_code.split('-')[0]))
        except:
            return np.nan
    if zip_code < 10000 or zip_code > 19999:
        return np.nan
    else:
        return str(zip_code)

In [60]:
# Apply correct_zip function to clean Incident Zip data
df['incident_zip'] = df['incident_zip'].apply(correct_zip)

In [62]:
#Remove rows from data that have incident zip as null i.e nan
df = df[df['incident_zip'].notnull()]

In [63]:
#Count of non-null values for every column 
df_columns = list(df.columns)
df[df_columns].count()

unique_key                2290849
created_date              2290849
closed_date               2290849
agency                    2290849
agency_name               2290849
complaint_type            2290849
descriptor                2290849
location_type             2032129
incident_zip              2290849
city                      2204719
status                    2290849
bbl                       2079037
borough                   2290849
open_data_channel_type    2290849
latitude                  2290849
longitude                 2290849
location                  2290849
day                       2290849
month                     2290849
day_of_week               2290849
hour                      2290849
closed_day                2290849
response_time             2290849
dtype: int64

In [64]:
#Closed date, Latitude, and Longitude all have missing values, best to remove the rows where data in those columns are missing
df = df[(df['latitude'].notnull()) & (df['longitude'].notnull()) & (df['closed_date'].notnull())]

In [65]:
#Count of non-null values for every column 
df_columns = list(df.columns)
df[df_columns].count()

unique_key                2290849
created_date              2290849
closed_date               2290849
agency                    2290849
agency_name               2290849
complaint_type            2290849
descriptor                2290849
location_type             2032129
incident_zip              2290849
city                      2204719
status                    2290849
bbl                       2079037
borough                   2290849
open_data_channel_type    2290849
latitude                  2290849
longitude                 2290849
location                  2290849
day                       2290849
month                     2290849
day_of_week               2290849
hour                      2290849
closed_day                2290849
response_time             2290849
dtype: int64

In [67]:
#As part of the EDA process, all columns should be explored to identify columns with messy data or nan
df['agency'].unique()

array(['DEP', 'NYPD', 'DSNY', 'DOHMH', 'DOT', 'HPD', 'DOB', 'TLC', 'DPR',
       'DCA', 'DOE', 'DHS', 'OTI', 'EDC'], dtype=object)

In [68]:
df['complaint_type'].unique()

array(['Air Quality', 'Noise - Street/Sidewalk', 'Noise - Residential',
       'Noise - Vehicle', 'Illegal Parking',
       'Request Large Bulky Item Collection', 'Noise - Commercial',
       'Blocked Driveway', 'Rodent', 'Street Condition', 'Heat/Hot Water',
       'General', 'Water Leak', 'Plumbing', 'Unsanitary Condition',
       'Noise - Park', 'Unsanitary Animal Pvt Property',
       'Sidewalk Condition', 'Paint/Plaster', 'Electric',
       'Electronics Waste Appointment', 'Dirty Condition',
       'Noise - Unspecified', 'Graffiti', 'Building/Use',
       'Non-Emergency Police Matter', 'Lead', 'Face Covering Violation',
       'Lost Property', 'Illegal Tree Damage', 'Drinking', 'Traffic',
       'Taxi Complaint', 'Drug Activity', 'Door/Window',
       'Flooring/Stairs', 'Sewer', 'Abandoned Vehicle',
       'Consumer Complaint', 'Illegal Dumping',
       'Traffic Signal Condition', 'Water System', 'Missed Collection',
       'General Construction/Plumbing', 'Litter Basket Request',
       'Street Sign - Damaged', 'Obstruction', 'Litter Basket Complaint',
       'Special Projects Inspection Team (Spit)', 'Dead Animal',
       'Maintenance Or Facility', 'Street Light Condition',
       'Vaccine Mandate Non-Compliance', 'Appliance',
       'Residential Disposal Complaint', 'Animal In A Park',
       'Street Sign - Dangling', 'Elevator', 'Bus Stop Shelter Complaint',
       'Animal-Abuse', 'Damaged Tree', 'Street Sign - Missing',
       'Violation Of Park Rules', 'Derelict Vehicles',
       'Broken Parking Meter', 'Real Time Enforcement', 'Boilers',
       'Noise - House Of Worship', 'Outside Building', 'Industrial Waste',
       'Curb Condition', 'For Hire Vehicle Complaint', 'Dead/Dying Tree',
       'Dumpster Complaint', 'Safety', 'Emergency Response Team (Ert)',
       'New Tree Request', 'Abandoned Bike', 'Illegal Posting',
       'Electrical', 'Water Quality', 'Outdoor Dining',
       'Overgrown Tree/Branches', 'Root/Sewer/Sidewalk Condition',
       'Bus Stop Shelter Placement', 'Lot Condition',
       'Street Sweeping Complaint', 'Institution Disposal Complaint',
       'Incorrect Data', 'Asbestos', 'Posting Advertisement',
       'Water Conservation', 'Disorderly Youth', 'Hazardous Materials',
       'Snow Or Ice', 'Sanitation Worker Or Vehicle Complaint',
       'Best/Site Safety', 'School Maintenance', 'Drinking Water',
       'Beach/Pool/Sauna Complaint', 'Unsanitary Pigeon Condition',
       'Private School Vaccine Mandate Non-Compliance',
       'Investigations And Discipline (Iad)', 'Adopt-A-Basket',
       'Commercial Disposal Complaint', 'E-Scooter',
       'Green Taxi Complaint', 'Taxi Compliment', 'Ahv Inspection Unit',
       'Bike Rack Condition', 'Scaffold Safety', 'Uprooted Stump',
       'Recycling Basket Complaint', 'Homeless Person Assistance',
       'Borough Office', 'Linknyc', 'Plant', 'For Hire Vehicle Report',
       'Cranes And Derricks', 'Cooling Tower', 'Wood Pile Remaining',
       'X-Ray Machine/Equipment', 'Oil Or Gas Spill',
       'Retailer Complaint', 'Special Natural Area District (Snad)',
       'Seasonal Collection', 'Facade Insp Safety Pgm',
       'Building Marshals Office', 'Bottled Water',
       'Dept Of Investigations', 'Dep Street Condition',
       'Noise - Helicopter', 'Building Condition', 'Radioactive Material',
       'Public Toilet', 'Dispatched Taxi Compliment',
       'Mass Gathering Complaint', 'Taxi Report',
       'Public Payphone Complaint', 'Covid-19 Non-Essential Construction',
       'Mosquitoes', 'Facades', 'Indoor Sewage', 'Dep Highway Condition',
       'Fhv Licensee Complaint', 'Transfer Station Complaint',
       'Taxi Licensee Complaint', 'Municipal Parking Facility',
       'Lifeguard', 'Building Drinking Water Tank', 'Internal Code',
       'Dep Sidewalk Condition', 'Special Operations', 'Ztestint',
       'Found Property', 'Highway Condition', 'Dsny Internal'],
      dtype=object)

In [69]:
df['city'].unique()

array(['NEW YORK', 'BROOKLYN', 'BRONX', 'FAR ROCKAWAY', 'WOODSIDE',
       'LITTLE NECK', 'ASTORIA', nan, 'STATEN ISLAND', 'HOLLIS',
       'COLLEGE POINT', 'JACKSON HEIGHTS', 'FRESH MEADOWS',
       'MIDDLE VILLAGE', 'FLUSHING', 'ELMHURST', 'CORONA', 'JAMAICA',
       'ARVERNE', 'EAST ELMHURST', 'WHITESTONE', 'OZONE PARK',
       'SOUTH OZONE PARK', 'REGO PARK', 'FOREST HILLS', 'QUEENS VILLAGE',
       'LONG ISLAND CITY', 'MASPETH', 'SAINT ALBANS',
       'SOUTH RICHMOND HILL', 'KEW GARDENS', 'RIDGEWOOD',
       'SPRINGFIELD GARDENS', 'RICHMOND HILL', 'SUNNYSIDE', 'ROSEDALE',
       'BAYSIDE', 'WOODHAVEN', 'OAKLAND GARDENS', 'MANHATTAN', 'QUEENS',
       'GLEN OAKS', 'CAMBRIA HEIGHTS', 'BELLEROSE', 'HOWARD BEACH',
       'FLORAL PARK', 'NEW HYDE PARK', 'BREEZY POINT', 'queens',
       'LAGUARDIA AIRPORT', 'Long Island City', 'Forest Hills', 'Bronx',
       'Brooklyn', 'New York', 'New York City', 'Ozone Park',
       'Queens Village', 'JAMAICA PLAIN', 'Jamaica'], dtype=object)

In [70]:
df['status'].unique()

array(['Closed', 'Assigned', 'Unspecified', 'Started', 'Pending', 'Open'],
      dtype=object)

In [71]:
df['borough'].unique()

array(['MANHATTAN', 'BROOKLYN', 'BRONX', 'QUEENS', 'STATEN ISLAND',
       'Unspecified'], dtype=object)

Columns with messy or missing data
City - contains some cities in uppercase and others in lowercase
status - contains nan values
Borough - contains 'Unspecified' boroughs

In [72]:
#looking at the unspecified boroughs, we want to be sure that removing data from df won't cause problems later on
df[df['borough']=='Unspecified'][['agency', 'city']]

        agency              city
1845      NYPD          NEW YORK
16970      DEP            QUEENS
49041      DEP            QUEENS
60140      DOT            QUEENS
78100      DOT            QUEENS
104374     DOT            QUEENS
140777     DEP            QUEENS
172283     DEP            QUEENS
208908     DOT            QUEENS
312033     DEP            QUEENS
327425     DOT           ASTORIA
336306     DOT           ASTORIA
346614    DSNY               NaN
346642    DSNY               NaN
347720     DEP            QUEENS
348247    DSNY               NaN
349949    NYPD               NaN
395144    NYPD               NaN
478923     DEP            QUEENS
517084    NYPD               NaN
532127     DOT               NaN
538456     DOT          NEW YORK
552240    DSNY            queens
578892     DOT            QUEENS
592482    NYPD          NEW YORK
606927     DOT               NaN
618563    DSNY               NaN
675215    NYPD               NaN
695361     DEP            QUEENS
695398     DEP            QUEENS
753368     DEP            QUEENS
763316     DOT               NaN
780428     DEP            QUEENS
801808     DEP            QUEENS
812434     DEP            QUEENS
831009     DEP            QUEENS
839752    NYPD               NaN
883806    NYPD               NaN
938430     DCA  Long Island City
1018451    DOT          BROOKLYN
1019117   NYPD               NaN
1051818   NYPD          NEW YORK
1061025    DEP            QUEENS
1125789   NYPD               NaN
1156813    DOT            QUEENS
1165548   NYPD               NaN
1190319    DEP            QUEENS
1231197    DOT            QUEENS
1245587    DOT            QUEENS
1293290   DSNY               NaN
1298958    DEP            QUEENS
1423612    DOT            QUEENS
1499443    DOT            QUEENS
1537988    DOT               NaN
1543554    DPR               NaN
1543583    DPR               NaN
1555799    DOT            QUEENS
1565226    DOT            QUEENS
1567426    DOT            QUEENS
1586720    DEP          NEW YORK
1588618    DOT            QUEENS
1594352   NYPD               NaN
1636570   DSNY               NaN
1643807   NYPD               NaN
1644763   NYPD               NaN
1657445    DOT            QUEENS
1764038   NYPD               NaN
1773435   DSNY               NaN
1792027    DOT            QUEENS
1854260    DOT            QUEENS
1854331    DOT            QUEENS
1854334    DOT            QUEENS
1856600    DOT            QUEENS
1864178    DOT            QUEENS
1890839    DOT            QUEENS
1897803   NYPD               NaN
1990259   NYPD               NaN
1994201   NYPD               NaN
2040790    DOT            QUEENS
2042544    DOT            QUEENS
2042607    DOT            QUEENS
2043101    DOT            QUEENS
2047729    DOT            QUEENS
2050192    DOT            QUEENS
2051154    DOT            QUEENS
2058431    DOT            QUEENS
2063096    DOT            QUEENS
2064125    DEP          NEW YORK
2067170    DOT            QUEENS
2071742    DOT            QUEENS
2079070    DOT            QUEENS
2079390   NYPD               NaN
2096279   DSNY               NaN
2166295   DSNY               NaN
2168306    DPR               NaN
2226296   NYPD               NaN
2252150   NYPD               NaN
2294608   DSNY               NaN
2298443   DSNY          NEW YORK
2342531   NYPD               NaN
2355442    DOT            QUEENS
2403040    DOT               NaN
2412191    DEP            QUEENS
2425931    DOT            QUEENS
2428215    DEP            QUEENS
2452857    DOT               NaN
2492906   NYPD               NaN
2511293   NYPD               NaN
2519221   NYPD               NaN
2527017   NYPD               NaN
2552865   NYPD               NaN
2565059    DOT            QUEENS
2614326   DSNY               NaN

In [76]:
# Majority of the data belongs to NYPD Agency and occurs in Staten Island
# To ensure I don't lose too much data from NYPD, I need to ensure this accounts for a neglegible number of NYPD
nypd_total = df[df['agency']=='NYPD']['borough'].count()
nypd_unspecified = df[(df['borough']=='Unspecified') & (df['agency']=="NYPD")]['borough'].count()
nypd_unspec_perct = nypd_unspecified/nypd_total*100
print("%1.3f"%nypd_unspec_perct)

0.002

In [78]:
#Boroughs that are unspecified are negligible that it can be removed
df = df[df['borough'] != 'Unspecified']

In [79]:
#Number of Status columns with nan
status_nan = len(df[df['status'].isnull()].index)
print(status_nan)

0

In [80]:
# Since some city values are represented both in uppercase and lowercase, it's better to have the city in the same case
# Convert all City Values to Camel Case
def camel_case(city):
    try:
        city = city.split(' ')
        city = ' '.join([x.lower().capitalize() for x in city])
        if city == 'Unknown':
            return np.nan
        else:
            return city
    except:
        return np.nan

In [81]:
# Apply camel_case function to City column
df['city'] = df['city'].apply(camel_case)

In [82]:
# Lets view the City values with nan
df[df['city'].isnull()].groupby('agency')['status'].count()

agency
DCA       1257
DHS         47
DOE         12
DOHMH       37
DOT      10291
DPR       2743
DSNY     12144
NYPD     55971
OTI         27
TLC       3556
Name: status, dtype: int64

In [83]:
# 10291 of Cities with nan value are of DOT Agency.
# It's better to know if this is significant before removing it
city_null_dot = len(df[(df['city'].isnull()) & (df['agency']=='DOT')].index)
dot_total = len(df[df['agency']=='DOT'].index)
city_null_dot_perct = (city_null_dot/dot_total)*100
print("%1.3f"%city_null_dot_perct)

7.477

In [86]:
# 7.477% is considerably a lot of NAN values and so Cities with nan can be removed from df
df = df[df['city'].notnull()]

In [88]:
# It would be useful to create a column to compute how long it takes to close a complaint
df['processing_time'] =  df['closed_date'] - df['created_date']

In [89]:

# Viewing the descriptive statistics on the Processing Time can give some insights on turn around time
df['processing_time'].describe()

count                       2204651
mean      6 days 14:28:12.673699828
std      19 days 06:07:35.682854298
min                 0 days 00:00:01
25%                 0 days 00:53:33
50%                 0 days 06:17:52
75%          4 days 01:16:54.500000
max               330 days 22:24:20
Name: processing_time, dtype: object

In [90]:
# Remove all data from df that have negative Processing Time
df = df[df['processing_time']>=datetime.timedelta(0,0,0)]

In [91]:
#Count of non-null values for every column 
df_columns = list(df.columns)
df[df_columns].count()

unique_key                2204651
created_date              2204651
closed_date               2204651
agency                    2204651
agency_name               2204651
complaint_type            2204651
descriptor                2204651
location_type             1946173
incident_zip              2204651
city                      2204651
status                    2204651
bbl                       2079028
borough                   2204651
open_data_channel_type    2204651
latitude                  2204651
longitude                 2204651
location                  2204651
day                       2204651
month                     2204651
day_of_week               2204651
hour                      2204651
closed_day                2204651
response_time             2204651
processing_time           2204651
dtype: int64

In [92]:
df.to_csv('311_data_2022.csv', index=False)